# Generated by Django 4.2.1 on 2023-06-01 22:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(to='app.course')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=25)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('instructions', models.CharField(max_length=255)),
                ('meeting_link', models.CharField(max_length=255)),
                ('interviewee_attended', models.BooleanField()),
                ('interviewer_attended', models.BooleanField()),
                ('status', models.IntegerField()),
                ('feedback', models.TextField(max_length=500)),
                ('rating', models.IntegerField()),
                ('interviewee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interviewee')),
                ('interviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interviewer')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slot')),
            ],
        ),
    ]
