# Generated by Django 4.2.1 on 2023-06-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('interviewer_id', models.IntegerField()),
                ('interviewee_id', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('students_notes', models.CharField(max_length=255)),
                ('admin_feedback', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('meeting_link', models.CharField(max_length=255)),
                ('meeting_status', models.CharField(max_length=1)),
                ('batch', models.CharField(max_length=255)),
                ('reminder_sent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewsOM',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('interviewer_id', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('students_notes', models.CharField(max_length=255)),
                ('admin_feedback', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('meeting_link', models.CharField(max_length=255)),
                ('meeting_status', models.CharField(max_length=1)),
                ('batch', models.CharField(max_length=255)),
                ('reminder_sent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField()),
                ('admin_id', models.IntegerField()),
                ('meeting_link', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('day', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=1)),
                ('user_id', models.IntegerField()),
                ('recurring_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SlotTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('roles', models.ManyToManyField(to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringMeeting',
            fields=[
                ('recurring_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('meeting_link', models.CharField(max_length=255)),
                ('instruction', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('availabilities', models.ManyToManyField(to='app.availability')),
            ],
        ),
        migrations.CreateModel(
            name='OneOnOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.CharField(max_length=255)),
                ('admin_id', models.IntegerField()),
                ('meeting_link', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=255)),
                ('slot_time', models.ManyToManyField(to='app.slottiming')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='recurringMeeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recurringmeeting'),
        ),
    ]
